<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Thumbico.Core\Thumbico.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Thumbico.Tests" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\Thumbico.Icons.ttf" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Strings.resx">
      <StronglyTypedFileName>$(IntermediateOutputPath)Strings.Designer.cs</StronglyTypedFileName>
      <StronglyTypedLanguage>CSharp</StronglyTypedLanguage>
      <StronglyTypedNamespace>Thumbico</StronglyTypedNamespace>
      <StronglyTypedClassName>Strings</StronglyTypedClassName>
    </EmbeddedResource>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>